from typing import List

class CashFlow:
    revenue: float
    cost: float
    def __init__(self, revenue: float, cost: float) -> None: ...

class MarketParameters:
    base_price: float
    price_vol: float
    discount_rate: float
    def __init__(self, base_price: float, price_vol: float, discount_rate: float) -> None: ...

class GeologyModel: ...

class MonteCarloEngine:
    def __init__(self, seed: int = ...) -> None: ...
    def run_geological_simulation(self, model: GeologyModel, num_iterations: int = ...) -> dict: ...
    def calculate_project_npv(self, flows: List[CashFlow], market: MarketParameters) -> dict: ...

class AustralianMiningModel:
    def __init__(self) -> None: ...
    def load_pilbara_data(self, data_file: str) -> None: ...
    def create_geology_model(self) -> GeologyModel: ...
    def simulate_water_contamination(self, source: dict, years: int) -> dict: ...

